default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { '1234' } %>

development:
  # primary:
  #   <<: *default
  #   database: <%= ENV.fetch('POSTGRES_DB_PRIMARY') { 'ca-data-center' } %>
  internal:
    <<: *default
    database: <%= ENV.fetch('POSTGRES_DB_INTERNAL') { 'ca-data-center-int' } %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  external:
    <<: *default
    database: <%= ENV.fetch('POSTGRES_DB_EXTERNAL') { 'ca-data-center-ext' } %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  # primary:
  #   <<: *default
  #   database: <%= ENV.fetch('POSTGRES_DB_PRIMARY') { 'ca-data-center' } %>
  internal:
    <<: *default
    database: <%= ENV.fetch('POSTGRES_DB_INTERNAL') { 'ca-data-center-int' } %>
  external:
    <<: *default
    database: <%= ENV.fetch('POSTGRES_DB_EXTERNAL') { 'ca-data-center-ext' } %>
