default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { 'cancer_sri-db' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>
  username: <%= ENV.fetch('DB_USER') { 'riseplus' } %>
  password: <%= ENV.fetch('DB_PASS') { 'riseplus' } %>
  database: <%= ENV.fetch('DB_NAME') { 'cancer_sri' } %>

development:
  primary:
    <<: *default
    database: <%= ENV.fetch('POSTGRES_DB_PRIMARY') { 'cancer_in_Srinagarind_hospital' } %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch('POSTGRES_DB_PRIMARY') { 'cancer_in_Srinagarind_hospital_production' } %>
  

